server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smooth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP 설정 추가
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000  # 20분 (MySQL wait_timeout보다 짧게)
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: smoothV2XSecretKeyForJWTTokenGenerationAndValidation2025
  expiration: 86400000  # 24시간

logging:
  level:
    com.smooth.backend: DEBUG